title: Text on Maps Help 
description: Help Docs for Searching and Annotationing Text on Maps in David Rumsey Map CollectionDavid Rumsey Map Collection
theme: just-the-docs
url: https://machines-reading-maps.github.io/rumsey

plugins:
  - jekyll-default-layout
